server:
  session-timeout: 1800
  port: 10000
spring:
  application:
    name: featureenv-front-example
  cloud:
    polaris:
      address: grpc://183.47.111.80:8091
      namespace: default
      enabled: true
logging:
  level:
    org.springframework.cloud.gateway: info
    com.tencent.cloud.polaris: debug
