server:
  session-timeout: 1800
  port: 48080
spring:
  application:
    name: DiscoveryCallerService
  cloud:
    polaris:
      address: grpc://183.47.111.80:8091
      namespace: default
      enabled: true
      discovery:
        enabled: true
        register: true
        heartbeat:
          enabled: true
        health-check-url: /discovery/service/caller/healthCheck
      stat:
        enabled: true
        port: 28081
    tencent:
      rpc-enhancement:
        reporter:
          enabled: true
#        pushgateway:
#          enabled: true
#          address: 127.0.0.1:9091
management:
  endpoints:
    web:
      exposure:
        include:
          - polaris-discovery
