server:
  session-timeout: 1800
  port: 59002
spring:
  application:
    name: gray-release-back
  cloud:
    polaris:
      address: grpc://183.47.111.80:8091
      namespace: default
      enabled: true
logging:
  level:
    org.springframework.cloud.gateway: info
    com.tencent.cloud.polaris: debug
