server:
  session-timeout: 1800
  port: 48083
spring:
  application:
    name: GatewayScgService
  cloud:
    tencent:
      plugin:
        scg:
          staining:
            enabled: true
            rule-staining:
              enabled: true
        router:
          feature-env:
            enabled: true
      metadata:
        content:
          a: 1
        transitive:
          - a
    polaris:
      address: grpc://183.47.111.80:8091
      namespace: default
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          'predicates[0]':
            name: Path
            args:
              patterns: '''/'' + serviceId + ''/**'''
          'filters[0]':
            name: RewritePath
            args:
              regexp: '''/'' + serviceId + ''/(?<remaining>.*)'''
              replacement: '''/$\{remaining}'''
          'filters[1]':
            name: Retry
            args:
              retries: 3
              exceptions:
                '[0]': '''java.net.ConnectException'''
                '[1]': '''java.io.IOException'''
              statuses:
                '[0]': '''BAD_GATEWAY'''
                '[1]': '''SERVICE_UNAVAILABLE'''
              series:
                '[0]': '''CLIENT_ERROR'''
              methods:
                '[0]': '''GET'''
                '[1]': '''POST'''
                '[2]': '''PUT'''
                '[3]': '''DELETE'''
              backoff:
                firstBackoff: '''100ms'''
                maxBackoff: '''500ms'''
                factor: 2
                basedOnPreviousValue: false
      routes:
        - id: GatewayCalleeService
          uri: lb://GatewayCalleeService
          predicates:
            - Path=/GatewayCalleeService/**
          filters:
            - StripPrefix=1
