server:
  session-timeout: 1800
  port: 48082
spring:
  application:
    name: GatewayCalleeService
  cloud:
    tencent:
      metadata:
        content:
          env: green
    polaris:
      address: grpc://183.47.111.80:8091
      namespace: default
