name: Test with Maven

on:
  push:
    branches:
      - 2022.0
      - 2021.0
      - 2020.0
      - hoxton
  pull_request:
    branches:
      - 2022.0
      - 2021.0
      - 2020.0
      - hoxton

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Test with Maven
        run: mvn -U -B clean test
