server:
  port: 48080
spring:
  application:
    name: polaris-circuitbreaker-webclient-example
  cloud:
    polaris:
      address: grpc://183.47.111.80:8091
      namespace: default
      enabled: true
      loadbalancer:
        enabled: true
      circuitbreaker:
        enabled: true
#      stat:
#        enabled: true
#        port: 28081
#    tencent:
#      rpc-enhancement:
#        enabled: true
#        reporter:
#          ignore-internal-server-error: true
#          series: server_error
#          statuses: gateway_timeout, bad_gateway, service_unavailable

logging:
  level:
    root: info
    com.tencent.cloud: debug

